apiVersion: v2
name: kube-fencing
description: Fencing implementation for Kubernetes
version: 2.3.0
appVersion: 2.3.0
icon: https://static.thenounproject.com/png/1281477-200.png
keywords:
  - fencing
  - fence
home: https://github.com/kvaps/kube-fencing
sources:
  - https://hub.docker.com/r/kvaps/kube-fencing-controller
  - https://hub.docker.com/r/kvaps/kube-fencing-switcher
  - https://hub.docker.com/r/kvaps/kube-fencing-agents
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
