{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fencing.fullname" . }}-controller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}-controller
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["list", "watch", "get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["podtemplates"]
    verbs: ["list", "watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ template "fencing.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "fencing.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}-controller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "get", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["deletecollection"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["list", "watch", "deletecollection"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fencing.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ template "fencing.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
