{{- if .Values.switcher.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: {{ template "fencing.fullname" . }}-switcher
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: {{ template "fencing.fullname" . }}-switcher
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: {{ template "fencing.fullname" . }}-switcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fencing.fullname" . }}-switcher
subjects:
  - kind: ServiceAccount
    name: {{ template "fencing.fullname" . }}-switcher
    namespace: {{ .Release.Namespace }}
{{- if .Values.podSecurityPolicy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: {{ template "fencing.fullname" . }}-switcher
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["{{ template "fencing.fullname" . }}"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: {{ template "fencing.fullname" . }}-switcher
roleRef:
  kind: Role
  name: {{ template "fencing.fullname" . }}-switcher
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "fencing.fullname" . }}-switcher
{{- end }}
{{- end }}
